version: 2
updates:
  # groups
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    ignore:
      - dependency-name: "@types*"
        update-types: ["version-update:semver-major"]
    groups:
      angular:
        applies-to: version-updates
        patterns:
          - '@angular*'
        update-types:
          - 'minor'
          - 'patch'
