kind: pipeline
type: docker
name: build and deploy
steps:
- name: build
  image: node:18.12.0-alpine
  commands:
  - npm ci
  - npm run build
  
- name: deploy
  image: cschlosser/drone-ftps
  environment:
    FTP_USERNAME:
      from_secret: ftp_username
    FTP_PASSWORD:
      from_secret: ftp_password
    PLUGIN_HOSTNAME: ftp.itsfiveoclockwhere.com:21
    PLUGIN_SRC_DIR: /dist/itsfiveoclockwhere
    PLUGIN_SECURE: true
    PLUGIN_VERIFY: false
    PLUGIN_CLEAN_DIR: true
  when:
    branch: 
      - master
